### ISSUE TITLE
Can this re-use dokku's nginx

### ISSUE THREAD

**Issue by desmond-dsouza** [pahaz/static-site-paas#1]
This looks great!! Thanks for sharing.

I already have dokku setup on digital-ocean, as some of my sites are dynamic. When you say "dokku compatible" what do you mean?

Can I reuse the nginx that is already installed with dokku? Would I need to change anything in your script for this? Looks like your line 21-23 reinstall nginx?

**Comment by pahaz** [comment]
> Hi! I use it with dokku without changes.
> This project is dokku compatible.
> 
> Thanks for your interest.

I found the draft in my mailbox. Sorry for the delay :(

**Comment by pahaz** [comment]
If you have any problem feel free to ask. I think it's too late to answer, really sorry.

**Comment by desmond-dsouza** [comment]
Hey, no problem, thanks for the reply!
